//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectTaskManagerEntities : DbContext
    {
        public ProjectTaskManagerEntities()
            : base("name=ProjectTaskManagerEntities")
        {
        }
    
       
    
        public virtual DbSet<tblProject> tblProjects { get; set; }
        public virtual DbSet<tblTask> tblTasks { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    }
}
