//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int TaskId { get; set; }
        public string Task { get; set; }
        public int ProjectID { get; set; }
        public bool IsParentTask { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> ParentTask { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int TaskOwner { get; set; }
        public string Status { get; set; }
    
        public virtual tblProject tblProject { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
